account_id = "af0012b153e06441ffcfa92ff0af2b79"
workers_dev = true
name = "magic-search"
compatibility_date = "2024-09-24"
main = "src/index.ts"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
# Default/development variables
ENVIRONMENT = "development"

[env.production]
name = "magic-search"
vars = { ENVIRONMENT = "production" }
